
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.text.html.parser.Element;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.DOMImplementation;
import org.w3c.dom.Document;
import org.w3c.dom.Text;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricky
 */
public class GUI_proyecto extends javax.swing.JFrame {

    Investigadores investigador;
    AdmArchivo ap;
    JFileChooser seleccionar = new JFileChooser();
    FileOutputStream salida;
    File archivo2;
    int rrn = 0;
    String nombreArchivo;
    Btree arbol = new Btree(5);

    public String GuardarArchivo() {
        String nombreArchivo2 = "";
        try {
            salida = new FileOutputStream(archivo2);
            nombreArchivo2 = seleccionar.getSelectedFile().getPath();
        } catch (Exception e) {
        }
        return nombreArchivo2;
    }
    //------------------------------------------------------------------------------------------
    Proyectos proyecto;
    AdmArchivo2 ap2;
    JFileChooser seleccionar2 = new JFileChooser();
    FileOutputStream salida2;
    File archivo3;
    int rrn2 = 0;
    String nombreArchivo2;
    Btree arbol2 = new Btree(5);

    public String GuardarArchivo2() {
        String nombreArchivo3 = "";
        try {
            salida2 = new FileOutputStream(archivo3);
            nombreArchivo3 = seleccionar2.getSelectedFile().getPath();
        } catch (Exception e) {
        }
        return nombreArchivo3;
    }

    public GUI_proyecto() {
        initComponents();
        if (seleccionar.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
            archivo2 = seleccionar.getSelectedFile();
            nombreArchivo = GuardarArchivo();
            JOptionPane.showMessageDialog(this, "El archivo fue guardado exitosamente");
            ap = new AdmArchivo(nombreArchivo);
        }

        if (seleccionar2.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
            archivo3 = seleccionar2.getSelectedFile();
            nombreArchivo2 = GuardarArchivo2();
            JOptionPane.showMessageDialog(this, "El archivo fue guardado exitosamente");
            ap2 = new AdmArchivo2(nombreArchivo2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Proyectos = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_nombreotema_proyecto = new javax.swing.JTextField();
        jtxt_investigador_proyectos = new javax.swing.JTextField();
        jtxt_fechainicio_proyecto = new javax.swing.JTextField();
        jtxt_fecha_finproyecto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcb_estado_proyecto = new javax.swing.JComboBox<>();
        jtxt_codigo_proyecto = new javax.swing.JTextField();
        jbt_agregar_proyecto = new javax.swing.JButton();
        jbt_buscar_proyecto = new javax.swing.JButton();
        Publicaciones = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxt_codigo_publicacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxt_proyecto_codigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxt_fecha_publicaciones = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jcbox_tipo_publicacion = new javax.swing.JComboBox<>();
        jbt_guardar_publicacion = new javax.swing.JButton();
        Carreras = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxt_codigo_carrera = new javax.swing.JTextField();
        jtxt_nombre_carrera = new javax.swing.JTextField();
        jcb_estado_carrera = new javax.swing.JComboBox<>();
        jbt_agregar_carrera = new javax.swing.JButton();
        Investigadores = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtxt_codigo_investigador = new javax.swing.JTextField();
        jtxt_nombre_investigador = new javax.swing.JTextField();
        jtxt_fecha_ingreso = new javax.swing.JTextField();
        jtxt_code_carrera = new javax.swing.JTextField();
        jcb_estado_investigador = new javax.swing.JComboBox<>();
        jbt_agregar_investigador = new javax.swing.JButton();
        jbt_buscar_investigador = new javax.swing.JButton();
        jbt_carreras = new javax.swing.JButton();
        jbt_investigadores = new javax.swing.JButton();
        jbt_proyectos = new javax.swing.JButton();
        jbt_publicaciones = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PROYECTOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CODIGO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("NOMBRE/TEMA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("INVESTIGADOR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("FECHA INICIO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("FECHA FIN");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ESTADO");

        jcb_estado_proyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iniciado", "Cancelado", "Publicado", "Rechazado" }));

        jbt_agregar_proyecto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_agregar_proyecto.setText("AGREGAR");
        jbt_agregar_proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_agregar_proyectoMouseClicked(evt);
            }
        });

        jbt_buscar_proyecto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_buscar_proyecto.setText("Buscar");
        jbt_buscar_proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_buscar_proyectoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jbt_agregar_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                            .addComponent(jbt_buscar_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxt_nombreotema_proyecto)
                                .addComponent(jtxt_investigador_proyectos)
                                .addComponent(jtxt_fechainicio_proyecto)
                                .addComponent(jtxt_fecha_finproyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(jtxt_codigo_proyecto)
                                .addComponent(jcb_estado_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtxt_codigo_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_nombreotema_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_investigador_proyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_fechainicio_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jtxt_fecha_finproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcb_estado_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_agregar_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_buscar_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProyectosLayout = new javax.swing.GroupLayout(Proyectos.getContentPane());
        Proyectos.getContentPane().setLayout(ProyectosLayout);
        ProyectosLayout.setHorizontalGroup(
            ProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ProyectosLayout.setVerticalGroup(
            ProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Publicaciones");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("CÓDIGO");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("PROYECTO (CÓDIGO)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("FECHA");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("TIPO");

        jcbox_tipo_publicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Revista", "Conferencia" }));

        jbt_guardar_publicacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_guardar_publicacion.setText("AGREGAR");
        jbt_guardar_publicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_guardar_publicacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_proyecto_codigo)
                            .addComponent(jtxt_codigo_publicacion)
                            .addComponent(jtxt_fecha_publicaciones)
                            .addComponent(jcbox_tipo_publicacion, 0, 149, Short.MAX_VALUE))))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbt_guardar_publicacion)
                .addGap(199, 199, 199))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxt_codigo_publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxt_proyecto_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxt_fecha_publicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jcbox_tipo_publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbt_guardar_publicacion)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PublicacionesLayout = new javax.swing.GroupLayout(Publicaciones.getContentPane());
        Publicaciones.getContentPane().setLayout(PublicacionesLayout);
        PublicacionesLayout.setHorizontalGroup(
            PublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PublicacionesLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PublicacionesLayout.setVerticalGroup(
            PublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("CARRERAS");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("CÓDIGO");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("NOMBRE");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("ESTADO");

        jcb_estado_carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jbt_agregar_carrera.setText("AGREGAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_nombre_carrera))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_codigo_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_estado_carrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jbt_agregar_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtxt_codigo_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtxt_nombre_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jcb_estado_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jbt_agregar_carrera)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CarrerasLayout = new javax.swing.GroupLayout(Carreras.getContentPane());
        Carreras.getContentPane().setLayout(CarrerasLayout);
        CarrerasLayout.setHorizontalGroup(
            CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CarrerasLayout.setVerticalGroup(
            CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("INVESTIGADORES");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("CÓDIGO");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("NOMBRE");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("FECHA DE INGRESO");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("CÓDIGO DE CARERRA");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("ESTADO");

        jcb_estado_investigador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jbt_agregar_investigador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_agregar_investigador.setText("AGREGAR");
        jbt_agregar_investigador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_agregar_investigadorMouseClicked(evt);
            }
        });

        jbt_buscar_investigador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_buscar_investigador.setText("BUSCAR");
        jbt_buscar_investigador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_buscar_investigadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_fecha_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxt_codigo_investigador))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxt_nombre_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_code_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jbt_agregar_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_estado_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbt_buscar_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtxt_codigo_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtxt_nombre_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtxt_fecha_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jtxt_code_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jcb_estado_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_agregar_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_buscar_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InvestigadoresLayout = new javax.swing.GroupLayout(Investigadores.getContentPane());
        Investigadores.getContentPane().setLayout(InvestigadoresLayout);
        InvestigadoresLayout.setHorizontalGroup(
            InvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InvestigadoresLayout.setVerticalGroup(
            InvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbt_carreras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_carreras.setText("Carreras");
        jbt_carreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_carrerasMouseClicked(evt);
            }
        });

        jbt_investigadores.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_investigadores.setText("Investigadores");
        jbt_investigadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_investigadoresMouseClicked(evt);
            }
        });

        jbt_proyectos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_proyectos.setText("Proyectos");
        jbt_proyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_proyectosMouseClicked(evt);
            }
        });

        jbt_publicaciones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_publicaciones.setText("Publicaciones");
        jbt_publicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_publicacionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_proyectos, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jbt_carreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_investigadores, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jbt_publicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_investigadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_carreras, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_proyectos, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jbt_publicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_proyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_proyectosMouseClicked
        Proyectos.setModal(true);
        Proyectos.pack();
        Proyectos.setLocationRelativeTo(this);
        Proyectos.setVisible(true);
    }//GEN-LAST:event_jbt_proyectosMouseClicked

    private void jbt_publicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_publicacionesMouseClicked
        Publicaciones.setModal(true);
        Publicaciones.pack();
        Publicaciones.setLocationRelativeTo(this);
        Publicaciones.setVisible(true);
    }//GEN-LAST:event_jbt_publicacionesMouseClicked

    private void jbt_guardar_publicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_guardar_publicacionMouseClicked

    }//GEN-LAST:event_jbt_guardar_publicacionMouseClicked

    private void jbt_agregar_proyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_agregar_proyectoMouseClicked
        ap2 = new AdmArchivo2(nombreArchivo2);
        ap2.setRegistro(new Proyectos(Integer.parseInt(jtxt_codigo_proyecto.getText()), jtxt_nombreotema_proyecto.getText(), Integer.parseInt(jtxt_investigador_proyectos.getText()), jtxt_fechainicio_proyecto.getText(), jtxt_fecha_finproyecto.getText(), jcb_estado_proyecto.getSelectedItem().toString()));
        proyecto = new Proyectos(Integer.parseInt(jtxt_codigo_proyecto.getText()), jtxt_nombreotema_proyecto.getText(), Integer.parseInt(jtxt_investigador_proyectos.getText()), jtxt_fechainicio_proyecto.getText(), jtxt_fecha_finproyecto.getText(), jcb_estado_proyecto.getSelectedItem().toString());
        arbol2.insert(Integer.parseInt(jtxt_codigo_proyecto.getText()), rrn2);
        rrn2++;
        ap2.getProyectos().add(proyecto);
        ap2.write_obj_registro();

    }//GEN-LAST:event_jbt_agregar_proyectoMouseClicked

    private void jbt_agregar_investigadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_agregar_investigadorMouseClicked
        ap = new AdmArchivo(nombreArchivo);
        ap.setRegistro(new Investigadores(jtxt_nombre_investigador.getText(), Integer.parseInt(jtxt_codigo_investigador.getText()), jtxt_fecha_ingreso.getText(), jtxt_code_carrera.getText(), jcb_estado_carrera.getSelectedItem().toString(), rrn));
        investigador = new Investigadores(jtxt_nombre_investigador.getText(), Integer.parseInt(jtxt_codigo_investigador.getText()), jtxt_fecha_ingreso.getText(), jtxt_code_carrera.getText(), jcb_estado_carrera.getSelectedItem().toString(), rrn);
        arbol.insert(Integer.parseInt(jtxt_codigo_investigador.getText()), rrn);
        rrn++;
        ap.getInvestigadores().add(investigador);
        ap.write_obj_registro();

    }//GEN-LAST:event_jbt_agregar_investigadorMouseClicked

    private void jbt_carrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_carrerasMouseClicked
        Carreras.setModal(true);
        Carreras.pack();
        Carreras.setLocationRelativeTo(this);
        Carreras.setVisible(true);
    }//GEN-LAST:event_jbt_carrerasMouseClicked


    private void jbt_investigadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_investigadoresMouseClicked
        Investigadores.setModal(true);
        Investigadores.pack();
        Investigadores.setLocationRelativeTo(this);
        Investigadores.setVisible(true);
        ap.write_arbol();
    }//GEN-LAST:event_jbt_investigadoresMouseClicked

    private void jbt_buscar_investigadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_buscar_investigadorMouseClicked
        int keycode = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el codigo del investigador"));
        ap.setArbol(arbol);
        if (ap.getArbol().search(ap.getArbol().root, keycode) == -1) {
            JOptionPane.showMessageDialog(null, "Registro no encontrado");
        } else {
            System.out.println("encontrado");
            File filename = new File("reg.bin");
            try {
                ap.read_registro_in_bytes(ap.getArbol().search(ap.getArbol().root, keycode), (int) filename.length());//encuentra la llave y nos devuelve el RRN asociado - multiplicamos por el tamaño del registro para encontrar la posicion exacta
                ap.write_registro_innewfile();
                investigador = ap.read_obj_registro();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI_proyecto.class.getName()).log(Level.SEVERE, null, ex);
            }

            //System.out.println(ap.getInvestigadores().get(arbol.search(ap.getArbol().root, keycode)).getNombreInvestigador());
            jtxt_nombre_investigador.setText(investigador.getNombreInvestigador());
            jtxt_codigo_investigador.setText(investigador.getCodigo() + "");
            jtxt_fecha_ingreso.setText(investigador.getFechaIngreso());
            jtxt_code_carrera.setText(investigador.getCodigoCarrera());
            jcb_estado_carrera.setSelectedItem(investigador.getEstado());
        }
    }//GEN-LAST:event_jbt_buscar_investigadorMouseClicked

    private void jbt_buscar_proyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_buscar_proyectoMouseClicked
        int keycode = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el codigo del investigador"));
        ap2.setArbol(arbol);
        if (ap2.getArbol().search(ap2.getArbol().root, keycode) == -1) {
            JOptionPane.showMessageDialog(null, "Registro no encontrado");
        } else {
            System.out.println("encontrado");
            File filename = new File("reg2.bin");
            try {
                ap2.read_registro_in_bytes(ap2.getArbol().search(ap2.getArbol().root, keycode), (int) filename.length());//encuentra la llave y nos devuelve el RRN asociado - multiplicamos por el tamaño del registro para encontrar la posicion exacta
                ap2.write_registro_innewfile();
                proyecto = ap2.read_obj_registro();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI_proyecto.class.getName()).log(Level.SEVERE, null, ex);
            }

            jtxt_codigo_proyecto.setText(proyecto.getCodigo() + "");
            jtxt_nombreotema_proyecto.setText(proyecto.getNombre());
            jtxt_investigador_proyectos.setText(proyecto.getInvestigador() + "");
            jtxt_fechainicio_proyecto.setText(proyecto.getFecha_ini());
            jtxt_fecha_finproyecto.setText(proyecto.getFecha_fin());
            jcb_estado_proyecto.setSelectedItem(proyecto.getEstado());
        }
    }//GEN-LAST:event_jbt_buscar_proyectoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Carreras;
    private javax.swing.JDialog Investigadores;
    private javax.swing.JDialog Proyectos;
    private javax.swing.JDialog Publicaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbt_agregar_carrera;
    private javax.swing.JButton jbt_agregar_investigador;
    private javax.swing.JButton jbt_agregar_proyecto;
    private javax.swing.JButton jbt_buscar_investigador;
    private javax.swing.JButton jbt_buscar_proyecto;
    private javax.swing.JButton jbt_carreras;
    private javax.swing.JButton jbt_guardar_publicacion;
    private javax.swing.JButton jbt_investigadores;
    private javax.swing.JButton jbt_proyectos;
    private javax.swing.JButton jbt_publicaciones;
    private javax.swing.JComboBox<String> jcb_estado_carrera;
    private javax.swing.JComboBox<String> jcb_estado_investigador;
    private javax.swing.JComboBox<String> jcb_estado_proyecto;
    private javax.swing.JComboBox<String> jcbox_tipo_publicacion;
    private javax.swing.JTextField jtxt_code_carrera;
    private javax.swing.JTextField jtxt_codigo_carrera;
    private javax.swing.JTextField jtxt_codigo_investigador;
    private javax.swing.JTextField jtxt_codigo_proyecto;
    private javax.swing.JTextField jtxt_codigo_publicacion;
    private javax.swing.JTextField jtxt_fecha_finproyecto;
    private javax.swing.JTextField jtxt_fecha_ingreso;
    private javax.swing.JTextField jtxt_fecha_publicaciones;
    private javax.swing.JTextField jtxt_fechainicio_proyecto;
    private javax.swing.JTextField jtxt_investigador_proyectos;
    private javax.swing.JTextField jtxt_nombre_carrera;
    private javax.swing.JTextField jtxt_nombre_investigador;
    private javax.swing.JTextField jtxt_nombreotema_proyecto;
    private javax.swing.JTextField jtxt_proyecto_codigo;
    // End of variables declaration//GEN-END:variables

}
